### ISSUE TITLE
Publish master as 0.17.2  to support Node 6.1.0

### ISSUE THREAD

**Issue by trueter** [libxmljs/libxmljs#406]
https://github.com/polotek/libxmljs/commit/70dd1d6c1504a1831f8a2deb78f40da6dc82c128 already landed in master. Please publish 0.17.2 for Node 6.1.0 support.

**Comment by rchipka** [comment]
We should probably also merge in #396 in for Windows support.

**Comment by BernhardBezdek** [comment]
Is there any reason why 0.17.2 isn't released yet? If so may I help?

**Comment by Maistho** [comment]
I support releasing v1.0.0 when this is fixed. Using <1.0.0 versions is silly for a package with >35k downloads per month.

**Comment by rchipka** [comment]
@Maistho makes sense according to SemVer: "Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable."

**Comment by trueter** [comment]
0.17.2 should be released anyway so people using a tilde semver specification also get the fix.

**Comment by Maistho** [comment]
@rchipka I wouldn't consider a project that is ~6 years old, with 550 commits and 33 releases to be in "initial development" 😉 
@trueter makes sense.

**Comment by defunctzombie** [comment]
It doesn't matter if we start with a 0 or 1; Semver sematics are stupid around this 0 vs 1 distinction. That being said, @rchipka feel free to bump this to 1.0.0 after updating to support node v6 and getting the appveryor stuff merged in. Seems like a good time as any to appease the pedantic versioners ;)

**Comment by Maistho** [comment]
@rchipka @defunctzombie Sorry if I come off as a "pedantic versioner" :stuck_out_tongue_winking_eye: 

I just think this could be as good time as any to release 1.0. :smiley:

**Comment by perrin4869** [comment]
@rchipka Any ETA when this will be landing?

**Comment by ericlw** [comment]
and how do I avoid the build errors until it is updated?

**Comment by Maistho** [comment]
@ericlw: Don't use node6, or use the latest (unreleased) version in your dependencies.

example: https://github.com/Maistho/gulp-xml-editor/blob/master/package.json#L29

**Comment by isamuelson** [comment]
any eta ?

**Comment by defunctzombie** [comment]
I have published 0.18.0 which builds and works on node v6

**Comment by koesbong** [comment]
@defunctzombie upgraded to node v6.2.0, npm v3.8.9, still doesn't work  :(  confirmed that it's also trying to install libxmljs@0.18.0. 

`npm ERR! Failed at the libxmljs@0.18.0 install script 'node-gyp rebuild'.`

**Comment by hildjj** [comment]
@koesbong, @drewatk  what OS?  Works for me on Ubuntu Wheezy and OSX.

**Comment by drewatk** [comment]
@hildjj I'm on Ubuntu 16.04

**Comment by Maistho** [comment]
@koesbong: do you get any error messages? Full error stack would be be useful to help debug

**Comment by koesbong** [comment]
@hildjj I am on Ubuntu 12.04 LTS.

@Maistho here's part of the error message:

```
../../nan/nan_implementation_12_inl.h:390:21: note: template<class T, class M> v8::Local<T> Nan::New(const v8::Persistent<S, M>&)
../../nan/nan_implementation_12_inl.h:395:21: note: template<class T, class M> v8::Local<T> Nan::New(const Nan::Persistent<T, M>&)

> libxmljs@0.18.0 install /opt/orbit/orbit-api/node_modules/libxmljs
> node-gyp rebuild

make: Entering directory `/opt/orbit/orbit-api/node_modules/libxmljs/build'
  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
  CC(target) Release/obj.target/libxml/vendor/libxml/catalog.o
  CC(target) Release/obj.target/libxml/vendor/libxml/chvalid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/dict.o
  CC(target) Release/obj.target/libxml/vendor/libxml/encoding.o
  CC(target) Release/obj.target/libxml/vendor/libxml/entities.o
  CC(target) Release/obj.target/libxml/vendor/libxml/error.o
  CC(target) Release/obj.target/libxml/vendor/libxml/globals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/hash.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLparser.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLtree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/legacy.o
  CC(target) Release/obj.target/libxml/vendor/libxml/list.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parser.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parserInternals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/pattern.o
  CC(target) Release/obj.target/libxml/vendor/libxml/relaxng.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX2.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX.o
  CC(target) Release/obj.target/libxml/vendor/libxml/tree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/threads.o
  CC(target) Release/obj.target/libxml/vendor/libxml/uri.o
  CC(target) Release/obj.target/libxml/vendor/libxml/valid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xinclude.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xlink.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlIO.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmemory.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmodule.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlreader.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlregexp.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlsave.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemas.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemastypes.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlstring.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlunicode.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlwriter.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xpath.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xpointer.o
  AR(target) Release/obj.target/vendor/libxml/xml.a
  COPY Release/xml.a
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
make: Leaving directory `/opt/orbit/orbit-api/node_modules/libxmljs/build'
...skipping...
../../nan/nan_implementation_12_inl.h:400:21: note: template<class T> v8::Local<T> Nan::New(const Nan::Global<T>&)
../../nan/nan_new.h:201:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New()
../../nan/nan_new.h:207:1: note: template<class T, class A0> typename Nan::imp::Factory<T>::return_t Nan::New(A0)
../../nan/nan_new.h:213:1: note: template<class T, class A0, class A1> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1)
../../nan/nan_new.h:219:1: note: template<class T, class A0, class A1, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2)
../../nan/nan_new.h:225:1: note: template<class T, class A0, class A1, class A2, class A3> typename Nan::imp::Factory<T>::return_t Nan::New(A0, A1, A2, A3)
../../nan/nan_new.h:237:1: note: template<class T> typename Nan::imp::Factory::return_t Nan::New(Nan::FunctionCallback, v8::Local<v8::Value>)
../../nan/nan_new.h:245:1: note: template<class T, class A2> typename Nan::imp::Factory<T>::return_t Nan::New(Nan::FunctionCallback, v8::Local<v8::Value>, A2)
../../nan/nan_new.h: In function 'v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Int32]':
../../nan/nan_new.h:29:1: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.2.0-23-generic-pae
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/orbit/orbit-api/node_modules/libxmljs
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "libxmljs"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.18.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.18.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.
```

**Comment by hildjj** [comment]
I did this:

```bash
docker run -it ubuntu:16.04 bash
apt-get update
apt-get upgrade
curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-get install nodejs build-essential
cd /tmp
npm install libxmljs
node -e 'console.log(require("libxmljs"))'
```

Works as expected.  Note: if you're installing the normal `nodejs` package from Ubuntu, you need to install `npm` separately, and create a symlink from `/usr/bin/nodejs` to `/usr/bin/node`, or everything will break.

**Comment by drewatk** [comment]
@Maistho Here is the full output of `npm install libxmljs`
```
> libxmljs@0.18.0 install /home/drew/projects/clientApp/node_modules/libxmljs
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/home/drew/projects/clientApp/node_modules/libxmljs/build'
  CC(target) Release/obj.target/libxml/vendor/libxml/buf.o
  CC(target) Release/obj.target/libxml/vendor/libxml/catalog.o
  CC(target) Release/obj.target/libxml/vendor/libxml/chvalid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/dict.o
  CC(target) Release/obj.target/libxml/vendor/libxml/encoding.o
../vendor/libxml/encoding.c: In function ‘xmlCharEncCloseFunc’:
../vendor/libxml/encoding.c:2856:12: warning: variable ‘handler_in_list’ set but not used [-Wunused-but-set-variable]
     int i, handler_in_list = 0;
            ^
  CC(target) Release/obj.target/libxml/vendor/libxml/entities.o
  CC(target) Release/obj.target/libxml/vendor/libxml/error.o
  CC(target) Release/obj.target/libxml/vendor/libxml/globals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/hash.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLparser.o
  CC(target) Release/obj.target/libxml/vendor/libxml/HTMLtree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/legacy.o
  CC(target) Release/obj.target/libxml/vendor/libxml/list.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parser.o
  CC(target) Release/obj.target/libxml/vendor/libxml/parserInternals.o
  CC(target) Release/obj.target/libxml/vendor/libxml/pattern.o
  CC(target) Release/obj.target/libxml/vendor/libxml/relaxng.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX2.o
  CC(target) Release/obj.target/libxml/vendor/libxml/SAX.o
  CC(target) Release/obj.target/libxml/vendor/libxml/tree.o
  CC(target) Release/obj.target/libxml/vendor/libxml/threads.o
  CC(target) Release/obj.target/libxml/vendor/libxml/uri.o
  CC(target) Release/obj.target/libxml/vendor/libxml/valid.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xinclude.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xlink.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlIO.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmemory.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlmodule.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlreader.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlregexp.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlsave.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemas.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlschemastypes.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlstring.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlunicode.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xmlwriter.o
  CC(target) Release/obj.target/libxml/vendor/libxml/xpath.o
In file included from ../vendor/libxml/xpath.c:462:0:
../vendor/libxml/timsort.h: In function ‘libxml_domnode_tim_sort_collapse’:
../vendor/libxml/timsort.h:405:65: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ((stack_curr == 2) && (stack[0].length + stack[1].length == size)) {
                                                                 ^
../vendor/libxml/timsort.h:397:19: warning: variable ‘BD’ set but not used [-Wunused-but-set-variable]
     int ABC, BCD, BD, CD;
                   ^
../vendor/libxml/xpath.c: In function ‘xmlXPathNodeCollectAndTest’:
../vendor/libxml/xpath.c:12406:28: warning: comparison between ‘xmlElementType {aka enum <anonymous>}’ and ‘xmlXPathTypeVal {aka enum <anonymous>}’ [-Wenum-compare]
       } else if (cur->type == type) {
                            ^
In file included from ../vendor/libxml/xpath.c:476:0:
../vendor/libxml/xpath.c: At top level:
../vendor/libxml/trionan.c:194:1: warning: ‘trio_is_special_quantity’ defined but not used [-Wunused-function]
 trio_is_special_quantity
 ^
../vendor/libxml/trionan.c:218:1: warning: ‘trio_is_negative’ defined but not used [-Wunused-function]
 trio_is_negative
 ^
../vendor/libxml/xpath.c: In function ‘xmlXPathCastNumberToString’:
../vendor/libxml/xpath.c:3197:7: warning: array subscript is above array bounds [-Warray-bounds]
   work[buffersize - 1] = 0;
       ^
  CC(target) Release/obj.target/libxml/vendor/libxml/xpointer.o
../vendor/libxml/xpointer.c: In function ‘xmlXPtrNewRangeNodePoint’:
../vendor/libxml/xpointer.c:451:21: warning: comparison between ‘xmlElementType {aka enum <anonymous>}’ and ‘enum <anonymous>’ [-Wenum-compare]
     if (start->type != XPATH_POINT)
                     ^
  AR(target) Release/obj.target/vendor/libxml/xml.a
  COPY Release/xml.a
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
make: g++: Command not found
xmljs.target.mk:101: recipe for target 'Release/obj.target/xmljs/src/libxmljs.o' failed
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 127
make: Leaving directory '/home/drew/projects/clientApp/node_modules/libxmljs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/drew/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.0-22-generic
gyp ERR! command "/home/drew/.nvm/versions/node/v6.2.0/bin/node" "/home/drew/.nvm/versions/node/v6.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/drew/projects/clientApp/node_modules/libxmljs
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/drew/.nvm/versions/node/v6.2.0/bin/node" "/home/drew/.nvm/versions/node/v6.2.0/bin/npm" "install" "libxmljs"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.18.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/drew/projects/clientApp/npm-debug.log

```

**Comment by hildjj** [comment]
@drewatk, you're missing g++.  `apt-get install build-essential`

**Comment by drewatk** [comment]
@hildjj That fixed it! Thank you very much

**Comment by koesbong** [comment]
@hildjj here's my ansible playbook

```
---
- name: Install dependencies
  hosts: all
  sudo: yes
  pre_tasks:
    - apt: update_cache=yes
      tags:
        - system
    - name: Install general packages
      apt: name={{ item }} state=present install_recommends=no
      with_items:
        - ack-grep
        - curl
        - monit
        - tmux
        - vim
      tags:
        - system

    - name: Install dependencies for ruby-build and node build
      apt: name={{ item }} install_recommends=no
      with_items:
        - build-essential
        - libcurl4-openssl-dev
        - libmysqlclient-dev
        - libncurses5-dev
        - libpq-dev
        - libreadline6-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
        - libyaml-dev
        - zlib1g-dev
        - make
      tags:
        - ruby
        - system
  roles:
    - role: base
```

And this is the node task
```
---
- name: curl for node
  shell: "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -"
  sudo: no

- name: get nodejs
  apt: name=nodejs install_recommends=no
```

So you're saying I still need to install npm separately?

**Comment by drewatk** [comment]
@hildjj Thank you very much! It now works when it's installing version 0.18.0

**Comment by hildjj** [comment]
@koesbong: no.  Your issue is probably the one described here: https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md

I was getting the same error as you on 12.04, but I followed the instructions for precise on the above page, and everything worked:

```
apt-get update
apt-get -y install curl
echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" >> /etc/apt/sources.list
echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.4 main" >> /etc/apt/sources.list
curl -s http://llvm.org/apt/llvm-snapshot.gpg.key | apt-key add -
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA9EF27F
apt-get update
apt-get install -y clang-3.4
cd /tmp/
CXX=clang++-3.4 CC=clang-3.4 npm install libxmljs
node -e 'console.log(require("libxmljs"))'
```

**Comment by koesbong** [comment]
@hildjj Ah OK, so would this issue be resolved if I use a different Ubuntu box, say 14.04?

**Comment by hildjj** [comment]
On Wheezy, you'd probably still need to install clang, according to that page.  Alternately, you can push for the precompiled binary system that comes with #407.  Then you might not need a compiler at all.

**Comment by hildjj** [comment]
I tried Ubuntu 14.04, and it worked just fine, although I had to install python:

```bash
apt-get update
apt-get upgrade
apt-get install -y curl python build-essential
curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-get install -y nodejs
cd /tmp
npm install libxmljs
node -e 'console.log(require("libxmljs"))'
```

**Comment by koesbong** [comment]
@hildjj woo! That worked, thanks so much for your help!
