### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by eg9402** [libxmljs/libxmljs#460]
> libxmljs@0.18.4 install /Users/ascc/develop/vagrant/working/P-Brain.ai/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.4 and node@6.10.0 (node-v48 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-darwin-x64.tar.gz

**Comment by ChaoticWeg** [comment]
Second this. Relevant log lines:

```
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.4 and node@6.10.2 (node-v48 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz
```

**Comment by pedro-nonfree** [comment]
Yes, this is the way to install libxmljs, so there's no binary and you have to compile.

Seems an incomplete log. Are you running debian/ubuntu? You have installed `apt-get install build-essential`?

By the way, that was my error related to "Install error" -> https://github.com/libxmljs/libxmljs/issues/465

**Comment by wotbstars** [comment]
It fails for me too. Docker container centos7. The same error randomly happens on different platforms (alpine, redhat). I belive it is in a way related to who is building the library. By some reason it is not ok to be built as root. Well on docker containers be a root is default and there is no point to create users.

Not saying it is build as a different user without issues. It fails sporadically even user is other than root but chances are it will fail as root are way higher (almost 100%).

On some platforms like alpine providing flag --unsafe-perm is helping but on centos it makes no effect.

```
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.4 and node@6.9.5 (node-v48 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz 
gyp http GET https://nodejs.org/download/release/v6.9.5/node-v6.9.5-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.9.5/node-v6.9.5-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1022:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Linux 4.4.27-boot2docker
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--loglevel=http" "--module=/opt/tc_base/Proj-Node/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/opt/tc_base/Proj-Node/node_modules/libxmljs/build/Release"
gyp ERR! cwd /opt/tc_base/Proj-Node/node_modules/libxmljs
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
npm ERR! code ELIFECYCLE
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:877:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm ERR! libxmljs@0.18.4 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs@0.18.4 install script 'node-pre-gyp install --fallback-to-build --loglevel http'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
```

**Comment by wotbstars** [comment]
This is the Docker file

FROM centos:centos7
RUN yum -y update
RUN yum -y install curl wget bash bash-completion sudo vim net-tools openssh redis python make libtool-ltdl java gcc-c++ libxslt-devel
RUN yum -y groupinstall 'Development Tools'

RUN curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
RUN yum -y install nodejs
RUN npm install -g n
RUN n 6.9.5
WORKDIR /tmp
RUN npm install libxmljs

try to build libxmljs in this container and it will crash

**Comment by wotbstars** [comment]
Wasted a day trying to build a container just to figure out that there is a bug in oracle virtual box that makes node lib archives occasionally (99% of the time) to arrive with a corrupted SSH signatures

every time signature has to be validated and it is corrupted build will fail

**Comment by rchipka** [comment]
Fixed in v0.18.7

**Comment by grofit** [comment]
I still get this issue:

```
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/node-v59-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.7 and node@9.0.0 (node-v59 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.7/node-v59-win32-x64.tar.gz
```

then a load of command guff and it blows up with:

```
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Code\Projects\project\node_modules\libxmljs\build\xmljs.vcxproj]
```

**Comment by grofit** [comment]
Crisis averted, it was a new build so installed node 9 if I go back to node 8.* it works as expected.
