### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by rhodgkins** [libxmljs/libxmljs#649]
Using latest version (1.0.11)

```js
const libXml = require('libxmljs')
const xmlString = `<?xml version="1.0" encoding="UTF-8"?>
<imsx_POXEnvelopeResponse xmlns="http://www.imsglobal.org/services/ltiv1p1/xsd/imsoms_v1p0">
  <imsx_POXHeader>
    <imsx_POXResponseHeaderInfo>
      <imsx_version>V1.0</imsx_version>
      <imsx_messageIdentifier/>
      <imsx_statusInfo>
        <imsx_codeMajor>success</imsx_codeMajor>
        <imsx_severity>status</imsx_severity>
        <imsx_description/>
        <imsx_messageRefIdentifier>ff119fad-1bdd-41af-b908-e7665abc4b28</imsx_messageRefIdentifier>
        <imsx_operationRefIdentifier>replaceResult</imsx_operationRefIdentifier>
        
      </imsx_statusInfo>
    </imsx_POXResponseHeaderInfo>
  </imsx_POXHeader>
  <imsx_POXBody><replaceResultResponse/></imsx_POXBody>
</imsx_POXEnvelopeResponse>`

const xml = libXml.parseXml(xmlString)

xml.namespaces()
```

Causes node to exit with a segmentation fault, however adding in a `xml.root()` before the `xml.namespaces()` fixes the issue (I think!).
It's not 100% reproducible, but I could do it 8 out of 10 times (just by pasting in the above into the node REPL).

**Comment by rhodgkins** [comment]
Ah interesting, I'm also seeing it more consistently in the cloud (on Google Cloud Run which I think is eventually back internally by K8?), my Docker image is `node:18-alpine` which (at the time of reproduction) resolves to `18.19.0-alpine3.19`.

**Comment by fuzing** [comment]
Same here... 100% failure resulting in core dump (ubuntu 22.04, AMD/Intel).   Also seeing numerous other oddities (e.g. element.attrs() only enumerating a single attribute when there are multiple)

**Comment by gokul-medipapel** [comment]
MIs there any fix available for the above issue?

**Comment by shunkica** [comment]
I am having the same issue. The only thing that fixes it for me is passing true as the first parameter (eg `xml.namespaces(true)` )

**Comment by emilisag** [comment]
Hello all, I saw that https://github.com/libxmljs/libxmljs/pull/655 was merged a couple of weeks ago. Is this issue now fixed? I pulled the latest version and it's still broken.

**Comment by shunkica** [comment]
> Hello all, I saw that #655 was merged a couple of weeks ago. Is this issue now fixed? I pulled the latest version and it's still broken.

It wasn't merged. I closed the pull request. This project no longer appears to be maintained.
